### ISSUE TITLE
'node' no such file or directory

### ISSUE THREAD

**Issue by JamesKingdom** [hughsk/pong#3]
Running pong on ubuntu, after installing

`root@vserv:~# pong --server 80`
`/usr/bin/env: ‘node’: No such file or directory`
`root@vserv:~# pong`
`/usr/bin/env: ‘node’: No such file or directory`
`root@vserv:~#`

**Comment by Rob-Rychs** [comment]
Did you install node? did you ever get this working?

**Comment by JamesKingdom** [comment]
Yea, node is installed, but installing just gives errors like this.

`root@devops:~# npm install -g pong'
'/usr/local/bin/pong -> /usr/local/lib/node_modules/pong/pong.js'

 'ws@0.4.32 install /usr/local/lib/node_modules/pong/node_modules/ws'
 (node-gyp rebuild 2> builderror.log) || (exit 0)'

'sh: 1: cannot create builderror.log: Permission denied'
'+ pong@0.1.1'
'added 19 packages in 6.494s'
'root@devops:~# pong --server 80'
'module.js:472'
'    throw err;'
'    ^'

'Error: Cannot find module 'socket.io/node_modules/socket.io-client
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pong/game.js:3:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)'

**Comment by Rob-Rychs** [comment]
I tried getting it working with every previous version of node<4.0 and i/o.js using nvm, no luck at all. It's a shame because this is such an awesome idea would be great to get it working again. Maybe one day...

**Comment by JamesKingdom** [comment]
stale
